### ISSUE TITLE
Some question about pascal voc test set

### ISSUE THREAD

**Issue by pcl111** [juntang-zhuang/ShelfNet#10]
Hi
I find your code is useful but there is question confuse me, when you test your code on pascal voc val set, your use _val_sync_transform function to crop and pad the image, but if we want to test the network performance on pascal voc test set, we should transform the image size to the original image size. can you share what should i do, thanks for your code.

**Comment by juntang-zhuang** [comment]
Hi, thanks for your interest. The evaluate-and-save is used only for validation, so we did not treat the preprocessing carefully. The reported results are generated from test.py for test dataset, and it’s evaluated on the server, so we cannot access ground truth of test set.
