### ISSUE TITLE
关于arxiv论文

### ISSUE THREAD

**Issue by hshustc** [juntang-zhuang/ShelfNet#11]
您好，我注意到您在arxiv的comments提到论文的结果不完整，撤掉了在arxiv的论文链接，那么这个repo的代码本身是否存在什么问题么？关于这个repo的代码现在应该参考哪篇论文呢？谢谢。

**Comment by juntang-zhuang** [comment]
It’s under submission, so we withdraw the arxiv version and changed title to follow anonymity rule. However, the old version paper still exists on arxiv. We will release new code and new paper after the acceptance.
