### ISSUE TITLE
How to load pretrained weights for training

### ISSUE THREAD

**Issue by poornimajd** [juntang-zhuang/ShelfNet#19]
Hi great work @juntang-zhuang .
I have trained the model on a custom dataset(say dataset1),and I also have another dataset(say dataset2),which is similar to dataset1,and hence I want to assign the custom dataset trained model weights as the initial weights for training the model on the dataset2.In the code I did not find where exactly we need to load the pretrained weights for training.
Any suggestion is appreciated 
Thank you

**Comment by juntang-zhuang** [comment]
Hi, I did not write resume in "city_lw" branch. You can insert code to load state dict after creating the model in train.py, like https://pytorch.org/tutorials/beginner/saving_loading_models.html. (PS, I'm not familiar with loading state in distributed mode, but I suppose it's similar to a centralized scenario)

**Comment by poornimajd** [comment]
Thanks for the quick reply! I will check it out.
