### ISSUE TITLE
The inference speed on Cityscapes

### ISSUE THREAD

**Issue by githubfragments** [juntang-zhuang/ShelfNet#2]
Nice work! I wonder how much time you speed to process the images of Cityscapes. Thus we can compare it with ICNet.

**Comment by juntang-zhuang** [comment]
Thanks for your interest. The code to test running speed is in experiments/segmentation/test_speed.py. 

I test speed with a single random tensor of size (1,3,512,512), repeat and average the running time. In this way, the running speed is related to the size of the image, but irrelevant to which dataset.

I did not re-implement ICNet in PyTorch and did not compare with it. But it can be tested with test_speed.py if the model is well defined in PyTorch.
