### ISSUE TITLE
RuntimeError: storage has wrong size: expected -4885659930368473377 got 589824

### ISSUE THREAD

**Issue by J-JunChen** [juntang-zhuang/ShelfNet#21]
Hi, Zhuang.
I meet a problem in /ShelfNet18_realtime/train.py 

```
 if it % 1000 == 0:
    ## dump the final model
    save_pth = osp.join(respth, 'shelfnet_model_it_%d.pth'%it)
    # net.cpu()
    # state = net.module.state_dict() if hasattr(net, 'module') else net.state_dict()
    # if dist.get_rank() == 0: torch.save(state, save_pth)
    torch.save(net.module.state_dict(),save_pth)

    if it % 1000 == 0 and it > 0:
        evaluate(checkpoint=save_pth)
```

when this code block runs in the following line `evaluate(checkpoint=save_pth)`, it appears the problem in /ShelfNet18_realtime/evaluate.py
 
```
def evaluate(respth='./res', dspth='/home/cjj/datasets/CityScapes/Fine', checkpoint=None):
...
if checkpoint is None:
        save_pth = osp.join(respth, 'model_final.pth')
    else:
        save_pth = checkpoint
    net.load_state_dict(torch.load(save_pth))
    net.cuda()
    net.eval()
...
```
and the line `net.load_state_dict(torch.load(save_pth))`  arises a error like that :
`RuntimeError: storage has wrong size: expected -4885659930368473377 got 589824`

Have you meet this problem like that? Thx

**Comment by juntang-zhuang** [comment]
Hi, I have not met this error before. Did you check PyTorch version? The repretrained weight is saved by PyTorch1.1. If you generate your own weights, I guess it's either related to PyTorch version or the file is corrupted. Perhaps you can train for only 1 epoch, then test if can resume using saved weights.
