### ISSUE TITLE
编译so的环境

### ISSUE THREAD

**Issue by luuuyi** [juntang-zhuang/ShelfNet#5]
你好，感谢你的工作。能问一下你调用的enclib_cpu.so和enclib_gpu.lib的编译环境么，使用过程中出现importerror问题

**Comment by juntang-zhuang** [comment]
Thanks for your interest. I used Ubuntu 16.04, CUDA 9.0, PyTorch 0.4.1, gcc 5.4.0. Please check if running "python setup.py install" will solve the problem. Or refer to ![Pytorch-encoding](https://github.com/zhanghang1989/PyTorch-Encoding) for installation of enclib. But in this implementation we did not use their encoding function, we just used their over-all framework for image processing, data loader and synchronized-bn et al.

**Comment by luuuyi** [comment]
谢谢，现在问题解决了。多问一句，同步BN如果不使用的话还能有那么高的性能么。

**Comment by juntang-zhuang** [comment]
I'm not sure. From my experience, the accuracy is very close, but it may converge faster with syncbn. I have not done extensive experiments on this, and this is just my impression.
