### ISSUE TITLE
import encoding issue : note:   template argument deduction/substitution failed:\nninja: build stopped: subcommand failed.\n"

### ISSUE THREAD

**Issue by saikatkundu36** [juntang-zhuang/ShelfNet#8]
Hi, 
 I tried implementing this arch. in my local server. I have installed all the dependencies mentioned and also ran the setup.py for torch-encoding from source as mentioned in link. But after that when I try run the demo.py in experiments/segmentation its  throwing the error as mentioned in the log file. For running the setup.py file in torch_encoding I changed the pytorch version from 0.4.1  to standard 1.0 and nightly.(Both gave the same error). Please help as the results are promising. Thanks in advance.
[log.txt](https://github.com/juntang-zhuang/ShelfNet/files/2806432/log.txt)

**Comment by juntang-zhuang** [comment]
Please ignore the demo.py file, it's forked from another repository, and I never used it. I'll remove it from the repository. Please try the test file with pre-trained weights.
