### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by kaixinxiao** [juntang-zhuang/ShelfNet#9]
I find a problem in train.py:
`# data transforms
        input_transform = transform.Compose([
            transform.ToTensor(),
            transform.Normalize([.485, .456, .406], [.229, .224, .225])])`
It seems different from paper saying:
> For data augmentation, the image is randomly flipped and scaled between 0.5 to 2, and randomly rotated between -10 and 10 degrees.
Should I add some data augmentation methods like paper's description? Thank you.

**Comment by juntang-zhuang** [comment]
Thanks for your interest. The data augmentation parameter parsing is not well written, some part of it is written within the dataset class. But our results in the old paper are generated from the same version in this repo. Besides, we have some updates in the code and updated results in our new version paper, but neither the new code nor the new paper can be published now., will release them in the future.
